function [rFit, rgof] = GyroidMaxForceFit(DR, R)
%CREATEFIT(DR,R)
%  Create a fit.
%
%  Data for 'Gyroid Max Force' fit:
%      X Input: DR
%      Y Output: R
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 07-Mar-2026 23:13:39


%% Fit: 'Gyroid Max Force'.

[xrData, yrData] = prepareCurveData( DR, R );

% Set up fittype and options.
ftr = fittype( 'poly1' );

% Fit model to data.
[rFit, rgof] = fit( xrData, yrData, ftr );

% % Create a figure for the plots.
% figure( 'Name', 'Gyroid Max Force' );
% 
% % Plot fit with data.
% subplot( 2, 1, 1 );
% h = plot( fitresult, xData, yData );
% legend( h, 'R vs. DR', 'Gyroid Max Force', 'Location', 'NorthEast', 'Interpreter', 'none' );
% % Label axes
% xlabel( 'DR', 'Interpreter', 'none' );
% ylabel( 'R', 'Interpreter', 'none' );
% grid on
% 
% % Plot residuals.
% subplot( 2, 1, 2 );
% h = plot( fitresult, xData, yData, 'residuals' );
% legend( h, 'Gyroid Max Force - residuals', 'Zero Line', 'Location', 'NorthEast', 'Interpreter', 'none' );
% % Label axes
% xlabel( 'DR', 'Interpreter', 'none' );
% ylabel( 'R', 'Interpreter', 'none' );
% grid on


