function [hFit, hgof] = HexagonMaxForceFit(DH, H)
%CREATEFIT(DH,H)
%  Create a fit.
%
%  Data for 'Hexagon Max Force' fit:
%      X Input: DH
%      Y Output: H
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 07-Mar-2026 23:16:09


%% Fit: 'Hexagon Max Force'.
[xhData, yhData] = prepareCurveData( DH, H );

% Set up fittype and options.
fth = fittype( 'poly1' );

% Fit model to data.
[hFit, hgof] = fit( xhData, yhData, fth );

% % Create a figure for the plots.
% figure( 'Name', 'Hexagon Max Force' );
% 
% % Plot fit with data.
% subplot( 2, 1, 1 );
% h = plot( fitresult, xData, yData );
% legend( h, 'H vs. DH', 'Hexagon Max Force', 'Location', 'NorthEast', 'Interpreter', 'none' );
% % Label axes
% xlabel( 'DH', 'Interpreter', 'none' );
% ylabel( 'H', 'Interpreter', 'none' );
% grid on
% 
% % Plot residuals.
% subplot( 2, 1, 2 );
% h = plot( fitresult, xData, yData, 'residuals' );
% legend( h, 'Hexagon Max Force - residuals', 'Zero Line', 'Location', 'NorthEast', 'Interpreter', 'none' );
% % Label axes
% xlabel( 'DH', 'Interpreter', 'none' );
% ylabel( 'H', 'Interpreter', 'none' );
% grid on


