function [gFit, ggof] = GridMaxForceFit(DG, G)
%CREATEFIT(DG,G)
%  Create a fit.
%
%  Data for 'Grid Max Force' fit:
%      X Input: DG
%      Y Output: G
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 07-Mar-2026 23:16:37


%% Fit: 'Grid Max Force'.
[xgData, ygData] = prepareCurveData( DG, G );

% Set up fittype and options.
ftg = fittype( 'poly1' );

% Fit model to data.
[gFit, ggof] = fit( xgData, ygData, ftg );

% % Create a figure for the plots.
% figure( 'Name', 'Grid Max Force' );
% 
% % Plot fit with data.
% subplot( 2, 1, 1 );
% h = plot( fitresult, xData, yData );
% legend( h, 'G vs. DG', 'Grid Max Force', 'Location', 'NorthEast', 'Interpreter', 'none' );
% % Label axes
% xlabel( 'DG', 'Interpreter', 'none' );
% ylabel( 'G', 'Interpreter', 'none' );
% grid on
% 
% % Plot residuals.
% subplot( 2, 1, 2 );
% h = plot( fitresult, xData, yData, 'residuals' );
% legend( h, 'Grid Max Force - residuals', 'Zero Line', 'Location', 'NorthEast', 'Interpreter', 'none' );
% % Label axes
% xlabel( 'DG', 'Interpreter', 'none' );
% ylabel( 'G', 'Interpreter', 'none' );
% grid on


